print ('Hello Lekan')
#name = ('Lekan')
#b = ('husband')
name = input ('pLEASE ENTER YOUR NAME : ')
print (5)
b = input ( 'ENTER YOUR SECOND NAME : ')
print(10)
print (str(name + b))
print (name)
print (b)
